package entity;
// Generated Dec 17, 2021, 3:50:40 PM by Hibernate Tools 5.4.32.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Post generated by hbm2java
 */
public class Post implements java.io.Serializable {

	private long id;
	private User user;
	private String title;
	private Date updatedAt;
	private Date publishedAt;
	private String content;
	private Set comments = new HashSet(0);
	private Set categories = new HashSet(0);

	public Post() {
	}

	public Post(long id, User user, String title) {
		this.id = id;
		this.user = user;
		this.title = title;
	}

	public Post(long id, User user, String title, Date updatedAt, Date publishedAt, String content, Set comments,
			Set categories) {
		this.id = id;
		this.user = user;
		this.title = title;
		this.updatedAt = updatedAt;
		this.publishedAt = publishedAt;
		this.content = content;
		this.comments = comments;
		this.categories = categories;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Date getPublishedAt() {
		return this.publishedAt;
	}

	public void setPublishedAt(Date publishedAt) {
		this.publishedAt = publishedAt;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Set getComments() {
		return this.comments;
	}

	public void setComments(Set comments) {
		this.comments = comments;
	}

	public Set getCategories() {
		return this.categories;
	}

	public void setCategories(Set categories) {
		this.categories = categories;
	}

}
