package entity;
// Generated Dec 17, 2021, 3:50:40 PM by Hibernate Tools 5.4.32.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private String firstname;
	private String lastname;
	private String mobile;
	private String email;
	private String password;
	private byte[] image;
	private String registerAt;
	private String lastLogin;
	private String activate;
	private String hashcode;

	public String getActivate() {
		return activate;
	}

	public void setActivate(String activate) {
		this.activate = activate;
	}

	public String getHashcode() {
		return hashcode;
	}

	public void setHashcode(String hashcode) {
		this.hashcode = hashcode;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public User() {
	}

	public User(long id, String email, String password, String registerAt) {
		this.id = id;
		this.email = email;
		this.password = password;
		this.registerAt = registerAt;
	}
	
	public User(long id, String firstname, String lastname, String mobile, String email, String password,
			String registerAt, String lastLogin) {
		this.id = id;
		this.firstname = firstname;
		this.lastname = lastname;
		this.mobile = mobile;
		this.email = email;
		this.password = password;
		this.registerAt = registerAt;
		this.lastLogin = lastLogin;
	}

	public User(long id, String firstname, String lastname, String mobile, String email, String password, byte[] image,
			String registerAt, String lastLogin) {
		this.id = id;
		this.firstname = firstname;
		this.lastname = lastname;
		this.mobile = mobile;
		this.email = email;
		this.password = password;
		this.image = image;
		this.registerAt = registerAt;
		this.lastLogin = lastLogin;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public String getRegisterAt() {
		return this.registerAt;
	}

	public void setRegisterAt(String registerAt) {
		this.registerAt = registerAt;
	}

	public String getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(String lastLogin) {
		this.lastLogin = lastLogin;
	}

}
